server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  kafka:
    producer:
      client-id: drones-service
      bootstrap-servers: ${KAFKA_SERVER}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

cron-expression: ${CRON_EXPRESSION:"*/30 * * * * *"}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:test}
  secret-key: ${MINIO_SECRET_KEY:password}
  bucket-name: ${MINIO_BUCKET_NAME:medication-images}

kafka:
  topic:
    name: ${KAFKA_TOPIC_NAME}