spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/drones_db;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    url: jdbc:h2:file:~/drones_db;AUTO_SERVER=TRUE
    user: sa
    password: password

cron-expression: "*/30 * * * * *"