server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  kafka:
    producer:
      client-id: drones-service
      bootstrap-servers: ${KAFKA_SERVER}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.yaml
    # https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html
    # If you do not specify any contexts in the CLI at runtime, every changeset in your changelog runs, even if they have contextFilters attached.
    contexts: default

cron-expression: ${CRON_EXPRESSION}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}

kafka:
  enabled: ${KAFKA_ENABLED:true}
  topic:
    name: ${KAFKA_TOPIC_NAME}