spring:
  h2:
    console:
      enabled: true
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driverClassName: ${db.driver}
  jpa:
    spring:
      jpa:
        database-platform: ${db.dialect}
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml